import React from "react";
import { StyleSheet, Text, View } from "react-native";
import AutoGeneratedCalendar from "../../components/CalendarRecap";

function CalendarScreen() {
  return (
   <>

   
<AutoGeneratedCalendar>
 
</AutoGeneratedCalendar>
   </>
  );
}





export default CalendarScreen;