import React from "react";
import { StyleSheet, Text, View } from "react-native";
import AutoGeneratedAgenda from "../../components/Agenda";

function CalendarScreen() {
  return (
<AutoGeneratedAgenda />
  );
}





export default CalendarScreen;