import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { selectUserData } from '../../redux/user/UserSelector';
import { fetchUserDetail } from '../../redux/user/UserSlice';
import { useAuthContext } from '../../contexts/AuthContext';
import { Image } from 'react-native-svg';
import { Text, View } from 'react-native';
import AutoGeneratedAgenda from '../../components/Agenda';
import { fetchPlanningDetail } from '../../redux/planing/PlaningSlice';
import { selectPlanningData } from '../../redux/planing/PlaningSelector';

function HomeScreen({navigation}) {
  const dispatch = useDispatch();
  const { planningDetail} = useSelector(selectPlanningData);
  const { user } = useAuthContext();
  const userId = user.id;

  useEffect(() => {
    dispatch(fetchPlanningDetail(userId));
  }, [dispatch, userId]);



  return (
    <View className="flex-1 bg-white rounded-lg shadow-lg">
      {/* En-tête avec logo et salutation */}
      <View className="flex-row items-center justify-center gap-4 mb-2">
        <Image
          source={require('../../assets/images/logo.png')}
          style={{width: 100, height: 100}}
        />
        <Text className="text-2xl font-bold text-[#639067]">
          Bonjour, {user.name} !
        </Text>
      </View>

      {/* Bordure supérieure */}
      <View className="border-4 border-[#639067] mb-4" />

      {/* Conteneur principa fd avec message */}

      <AutoGeneratedAgenda />
    </View>
  );
}

export default HomeScreen;
