import {useRoute} from '@react-navigation/native';
import React from 'react';
import {Button, Image, Pressable, Text, TouchableOpacity, View} from 'react-native';
import {useSelector} from 'react-redux';
import {selectUserData} from '../../redux/user/UserSelector';
import { Agenda, Calendar } from 'react-native-calendars';
import AutoGeneratedAgenda from '../../components/Agenda';


function HomeScreen({navigation}) {
  const route = useRoute();
  const {userId} = route.params || {};
  const {userDetail} = useSelector(selectUserData);
  const nickname = userDetail?.name ?? 'Pas de pseudo';

  return (
    <View className="flex-1 bg-white rounded-lg shadow-lg">
      {/* En-tête avec logo et salutation */}
      <View className="flex-row items-center justify-center gap-4 mb-2">
        <Image
          source={require('../../assets/images/logo.png')}
          style={{width: 100, height: 100}}
        />
        <Text className="text-2xl font-bold text-[#639067]">
          Bonjour, {nickname} !
 
        </Text>
      </View>

      {/* Bordure supérieure */}
      <View className="border-4 border-[#639067] mb-4" />

      {/* Conteneur principa fd avec message */}
    
   

   <AutoGeneratedAgenda />

 
    </View>  
  );
}

export default HomeScreen;
