import React, {useState, useCallback, useEffect} from 'react';
import {
  View,
  Text,
  Pressable,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import {useNavigation, useRoute} from '@react-navigation/native';
import Icon from 'react-native-vector-icons/Entypo';
import {PanGestureHandler, RefreshControl} from 'react-native-gesture-handler';


const AutoGeneratedCalendar = () => {
  const navigation = useNavigation();
  const route = useRoute();
  const {userId} = route.params || {};
  const [items, setItems] = useState({});
  const [currentDate, setCurrentDate] = useState(new Date());
  const [refreshing, setRefreshing] = React.useState(false);
  const [gestureHandled, setGestureHandled] = useState(false);
  const itemsArray = Object.entries(items);

  useEffect(() => {
    loadItems(currentDate);
  }, [loadItems, currentDate]);

  //----------Gestion du rendu des cards

  const loadItems = useCallback(date => {
    const newItems = {};
    const startDate = new Date(date);
    for (let i = 0; i < 8; i++) {
      const time = startDate.getTime() + i * 24 * 60 * 60 * 1000;
      const strTime = timeToString(time);
      newItems[strTime] = [{name: 'Pas de repas prévu !', timestamp: time}];
    }
    setItems(newItems);
  }, []);

  //-----------------Changement de date ------------
  const changeDays = increment => {
    const newDate = new Date(currentDate);
    newDate.setDate(newDate.getDate() + increment * 8);
    setCurrentDate(newDate);
  };

  //--------------Formatage des dates -------------

  const formatDateRange = () => {
    const startDate = new Date(currentDate);
    const endDate = new Date(currentDate);
    endDate.setDate(endDate.getDate() + 7);
    return `${formatDateMonth(startDate)} - ${formatDateDay(endDate)}`;
  };

  const timeToString = time => {
    const date = new Date(time);
    return date.toISOString().split('T')[0];
  };

  const formatDate = dateString => {
    const date = new Date(dateString);
    const options = {weekday: 'short', day: 'numeric'};
    return date.toLocaleDateString('fr-FR', options);
  };

  const formatDateMonth = date => {
    const options = {day: 'numeric', month: 'short'};
    return date.toLocaleDateString('fr-FR', options);
  };
  const formatDateDay = dateDay => {
    const options = {day: 'numeric', month: 'short'};
    return dateDay.toLocaleDateString('fr-FR', options);
  };

  //---------------------------------------------

  //--------------- Gestes de balayage-------------

  const handleGestureEvent = ({nativeEvent}) => {
    if (!gestureHandled) {
      if (nativeEvent.translationX > 50) {
        changeDays(-1); // Balayage vers la droite
        setGestureHandled(true); // Bloque d'autres gestes jusqu'à la fin de celui-ci
      } else if (nativeEvent.translationX < -50) {
        changeDays(1); // Balayage vers la gauche
        setGestureHandled(true); // Bloque d'autres gestes jusqu'à la fin de celui-ci
      }
    }
  };

  const handleGestureEnd = ({nativeEvent}) => {
    // Si le geste est terminé (ex: STATE.END), on réinitialise le blocage
    if (nativeEvent.state === 5) {
      // 5 correspond à "State.END" dans react-native-gesture-handler
      setGestureHandled(false); // Réinitialise l'état après la fin du geste
    }
  };

  //-----------------------------------------------

  //------------------Rendu des Cards--------
  const renderItem = (item, date) => {
    return (
      <Pressable
        style={styles.cardContainer}
        onPress={() =>
          navigation.navigate('MealPlannerScreen', {userId: userId, date: date})
        }>
        <View style={styles.item}>
          <Text style={styles.dateText}>{formatDate(date)}</Text>
          <Text style={styles.itemText}>{item.name}</Text>
          <View style={styles.border} />
          <Text style={styles.timeText}></Text>
          <View style={styles.border} />
          <Text style={styles.timeText}>
          
          </Text>
        </View>
      </Pressable>
    );
  };

  //--------------- Refresh pour retrouver la page du jour ---------------
  const onRefresh = React.useCallback(() => {
    setRefreshing(true);

    setTimeout(() => {
      const today = new Date();
      setCurrentDate(today); // Réinitialisez currentDate à aujourd'hui
      // Rechargez les éléments pour la date d'aujourd'hui
      loadItems(today);
      setRefreshing(false);
    }, 1000);
  }, []);

  //--------------Rendu du composant----------------
  return (
    // <PanGestureHandler
    // onGestureEvent={handleGestureEvent}
    // onHandlerStateChange={handleGestureEnd}>
    <ScrollView
      style={styles.container}
      refreshControl={
        <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
      }>
      <Text className="font-kaushan text-3xl text-[#639067] text-center p-5">
        Calendrier
      </Text>
      <View style={styles.centerContainer}>
        <View style={styles.monthContainer}>
          <TouchableOpacity
            onPress={() => changeDays(-1)}
            style={styles.monthButton}>
            <Icon name="triangle-left" size={24} color="white" />
          </TouchableOpacity>
          <View style={styles.monthTextContainer}>
            <Text style={styles.monthText}>{formatDateRange()}</Text>
          </View>
          <TouchableOpacity
            onPress={() => changeDays(1)}
            style={styles.monthButton}>
            <Icon name="triangle-right" size={24} color="white" />
          </TouchableOpacity>
        </View>
      </View>
      <View style={styles.grid}>
        {itemsArray.map(([dateKey, dateItems], index) => (
          <View key={dateKey} style={styles.column}>
            {renderItem(dateItems[0], dateKey)}
          </View>
        ))}
      </View>
    </ScrollView>
    // </PanGestureHandler>
  );
};

const styles = {
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  monthContainer: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#639067',
    borderRadius: 40,
    paddingHorizontal: 2,
    paddingVertical: 3,
    width: '65%',
  },
  monthTextContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthButton: {
    padding: 9
  },
  border: {
    width: '80%',
    alignSelf: 'center',
    height: 2,
    backgroundColor: '#639067',
    marginTop: 5,
  },
  monthText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
  },
  centerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  grid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  column: {
    width: '50%',
    paddingHorizontal: 10,
  },
  cardContainer: {
    flex: 1,
    marginTop: 20,
    marginBottom: 10,
    paddingVertical: 10,
  },
  item: {
    backgroundColor: '#EFEFEF',
    borderRadius: 8,
    borderColor: '#dcdcdc',
    borderWidth: 1,
    paddingVertical: 15,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    flexGrow: 1,
  },
  dateText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#639067',
    marginBottom: 10,
  },
  dateText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#639067',
    marginBottom: 5,
    position: 'absolute',
    top: -20,
    left: 40,
  },

  itemText: {
    color: '#888',
    fontSize: 14,
    fontWeight: '500',
    flexWrap: 'wrap', // Permet au texte de passer à la ligne
  },
  border: {
    borderBottomWidth: 1,
    borderBottomColor: '#dcdcdc',
    marginVertical: 5,
  },
  timeText: {
    color: '#888',
    fontSize: 12,
    marginTop: 5,
  },
  scrollViewContent: {
    flexGrow: 1,
  },
  centerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#639067',
    marginBottom: 10,
  },
};

export default AutoGeneratedCalendar;
